// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioAficionado.Infraestructura.Persistencia;

#nullable disable

namespace RadioAficionado.Infraestructura.Sqlite.Migraciones
{
    [DbContext(typeof(ContextoRadioAficionado))]
    [Migration("20260323105241_AgregarCamposSincronizacion")]
    partial class AgregarCamposSincronizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RadioAficionado.Dominio.Activaciones.Activacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoActivacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicativoActivador")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizador")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoActivacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EstadoActivacion");

                    b.HasIndex("FechaInicio");

                    b.HasIndex("IndicativoActivador");

                    b.HasIndex("Referencia");

                    b.HasIndex("TipoActivacion");

                    b.ToTable("Activaciones", (string)null);
                });

            modelBuilder.Entity("RadioAficionado.Dominio.Entidades.Qso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivacionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<long>("Frecuencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndicativoContacto")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicativoPropio")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizadorContacto")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Potencia")
                        .HasColumnType("REAL");

                    b.Property<string>("SenalEnviada")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenalRecibida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ActivacionId");

                    b.HasIndex("FechaHoraInicio");

                    b.HasIndex("Frecuencia");

                    b.HasIndex("IndicativoContacto");

                    b.HasIndex("IndicativoPropio");

                    b.HasIndex("Sincronizado");

                    b.ToTable("Qsos", (string)null);
                });

            modelBuilder.Entity("RadioAficionado.Dominio.Entidades.Qso", b =>
                {
                    b.HasOne("RadioAficionado.Dominio.Activaciones.Activacion", null)
                        .WithMany("Qsos")
                        .HasForeignKey("ActivacionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RadioAficionado.Dominio.Activaciones.Activacion", b =>
                {
                    b.Navigation("Qsos");
                });
#pragma warning restore 612, 618
        }
    }
}
